[build]
  base    = "bgmi-tournament/frontend"
  command = "npm run build"
  publish = "bgmi-tournament/frontend/dist"

[build.environment]
  VITE_API_URL = "https://bgmi-backend-2cnu.onrender.com"

[[redirects]]
  from    = "/api/*"
  to      = "https://bgmi-backend-2cnu.onrender.com/api/:splat"
  status  = 200
  force   = true
  headers = {X-Forwarded-Host = "bgmiarena.netlify.app"}

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
